name: 'Kernel Signer'
author: 'EyeCantCU'
description: 'Signs kernel in image via Podman'
inputs:
  image:
    description: 'Image containing kernel'
    required: true
  privkey:
    description: 'Private key, path to private key, or URL to retrieve private key'
    default: './certs/private_key.priv.test'
    required: true
  pubkey:
    description: 'Public key, path to public key, or URL to retrieve public key'
    default: './certs/public_key.der.test'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    IMAGE: ${{ inputs.image }}
    PRIVKEY: ${{ inputs.privkey }}
    PUBKEY: ${{ inputs.pubkey }}
