name: 'Kernel Signer'
author: 'EyeCantCU'
description: 'Signs kernel in image via Podman'
inputs:
  image:
    description: 'Image containing kernel'
    required: true
  privkey:
    description: 'Private key, path to private key, or URL to retrieve private key'
    default: '/etc/pki/kernel/private/private_key.priv'
    required: true
  pubkey:
    description: 'Public key, path to public key, or URL to retrieve public key'
    default: '/etc/pki/kernel/public/public_key.der'
    required: true
runs:
  using: "composite"
  steps:
    - name: Sign kernel
      shell: bash
      run: |
        CONTAINER_ID=$(podman run --replace --name ${{ inputs.image }} -dt ${{ inputs.image }})
        podman cp ./sign-kernel.sh ${{ inputs.image }}:/tmp/sign-kernel.sh
        podman exec -e PRIVKEY=${{ inputs.privkey }} -e PUBKEY=${{ inputs.pubkey }} ${{ inputs.image }} /tmp/sign-kernel.sh
        buildah commit $CONTAINER_ID ${{ inputs.image }}
